################################################################################
# CMakeLists.txt
#
# Created on: Dec 6, 2004
# Copyright Martin Wojtczyk <martin.wojtczyk@gmail.com>
################################################################################
FIND_PATH(COIN_INCLUDE_DIR Inventor/So.h
	${CMAKE_INCLUDE_PATH}
	${CMAKE_FRAMEWORK_PATH}
	$ENV{COINDIR}/include
	$ENV{COIN3DDIR}/include
	/usr/local/coin/include
	/usr/local/Coin/include
	/usr/local/include
	/usr/include
	$ENV{ProgramFiles}/Coin3D-2/include
)

IF (NOT COIN_INCLUDE_DIR_FOUND)
	IF (COIN_INCLUDE_DIR)
		MESSAGE(STATUS "Looking for Coin3D headers -- found " ${COIN_INCLUDE_DIR}/Inventor/So.h)
		SET(COIN_INCLUDE_DIR_FOUND 1 CACHE INTERNAL "Coin3D headers found")
	ELSE (COIN_INCLUDE_DIR)
		MESSAGE(FATAL_ERROR 
			"-- Looking for Coin3D headers -- not found\n"
			"Please install Coin3D http://www.coin3d.org/ or adjust CMAKE_INCLUDE_PATH\n"
			"e.g. cmake -DCMAKE_INCLUDE_PATH=/path-to-Coin/include ..."
		)
	ENDIF (COIN_INCLUDE_DIR)
ENDIF (NOT COIN_INCLUDE_DIR_FOUND)

FIND_LIBRARY(COIN_LIBRARY_RELEASE
	NAMES coin3 Coin coin2 Inventor
	PATHS
	${CMAKE_LIBRARY_PATH}
	${CMAKE_FRAMEWORK_PATH}
	$ENV{COINDIR}/lib
	$ENV{COIN3DDIR}/lib
	/usr/local/coin/lib
	/usr/local/lib
	/usr/lib
	$ENV{ProgramFiles}/Coin3D-2/lib
)

FIND_LIBRARY(COIN_LIBRARY_STATIC_RELEASE
	NAMES coin3s
	PATHS
	${CMAKE_LIBRARY_PATH}
	${CMAKE_FRAMEWORK_PATH}
	$ENV{COINDIR}/lib
	$ENV{COIN3DDIR}/lib
	/usr/local/coin/lib
	/usr/local/lib
	/usr/lib
	$ENV{ProgramFiles}/Coin3D-2/lib
)

FIND_LIBRARY(COIN_LIBRARY_DEBUG
	NAMES coin3d Coind coin2d
	PATHS
	${CMAKE_LIBRARY_PATH}
	${CMAKE_FRAMEWORK_PATH}
	$ENV{COINDIR}/lib
	$ENV{COIN3DDIR}/lib
	/usr/local/coin/lib
	/usr/local/lib
	/usr/lib
	$ENV{ProgramFiles}/Coin3D-2/lib
)

FIND_LIBRARY(COIN_LIBRARY_STATIC_DEBUG
	NAMES coin3sd
	PATHS
	${CMAKE_LIBRARY_PATH}
	${CMAKE_FRAMEWORK_PATH}
	$ENV{COINDIR}/lib
	$ENV{COIN3DDIR}/lib
	/usr/local/coin/lib
	/usr/local/lib
	/usr/lib
	$ENV{ProgramFiles}/Coin3D-2/lib
)

IF (COIN_LIBRARY_DEBUG AND NOT COIN_LIBRARY_RELEASE)
	SET(COIN_LIBRARY ${COIN_LIBRARY_DEBUG})
ENDIF (COIN_LIBRARY_DEBUG AND NOT COIN_LIBRARY_RELEASE)

IF (COIN_LIBRARY_RELEASE AND NOT COIN_LIBRARY_DEBUG)
	SET(COIN_LIBRARY ${COIN_LIBRARY_RELEASE})
ENDIF (COIN_LIBRARY_RELEASE AND NOT COIN_LIBRARY_DEBUG)

IF (COIN_LIBRARY_DEBUG AND COIN_LIBRARY_RELEASE)
	SET(COIN_LIBRARY debug ${COIN_LIBRARY_DEBUG} optimized ${COIN_LIBRARY_RELEASE})
ENDIF (COIN_LIBRARY_DEBUG AND COIN_LIBRARY_RELEASE)


IF (COIN_LIBRARY_STATIC_DEBUG AND NOT COIN_LIBRARY_STATIC_RELEASE)
	SET(COIN_LIBRARY_STATIC ${COIN_LIBRARY_STATIC_DEBUG})
ENDIF (COIN_LIBRARY_STATIC_DEBUG AND NOT COIN_LIBRARY_STATIC_RELEASE)

IF (COIN_LIBRARY_STATIC_RELEASE AND NOT COIN_LIBRARY_STATIC_DEBUG)
	SET(COIN_LIBRARY_STATIC ${COIN_LIBRARY_STATIC_RELEASE})
ENDIF (COIN_LIBRARY_STATIC_RELEASE AND NOT COIN_LIBRARY_STATIC_DEBUG)

IF (COIN_LIBRARY_STATIC_DEBUG AND COIN_LIBRARY_STATIC_RELEASE)
	SET(COIN_LIBRARY_STATIC debug ${COIN_LIBRARY_STATIC_DEBUG} optimized ${COIN_LIBRARY_STATIC_RELEASE})
ENDIF (COIN_LIBRARY_STATIC_DEBUG AND COIN_LIBRARY_STATIC_RELEASE)


IF (COIN_LIBRARY_STATIC AND NOT COIN_LIBRARY)
	set(COIN_LIBRARY ${COIN_LIBRARY_STATIC})
ENDIF (COIN_LIBRARY_STATIC AND NOT COIN_LIBRARY)

IF (COIN_INCLUDE_DIR AND COIN_LIBRARY)
	SET(COIN_FOUND TRUE)
ENDIF (COIN_INCLUDE_DIR AND COIN_LIBRARY)

IF (NOT COIN_LIBRARY_FOUND)
	IF (COIN_LIBRARY)
		MESSAGE(STATUS "Looking for Coin3D library -- found " ${COIN_LIBRARY})
		SET(COIN_LIBRARY_FOUND 1 CACHE INTERNAL "Coin3D library found")
	ELSE (COIN_LIBRARY)
		MESSAGE(FATAL_ERROR 
			"-- Looking for Coin3D library -- not found\n"
			"Please install Coin3D http://www.coin3d.org/ or adjust CMAKE_LIBRARY_PATH\n"
			"e.g. cmake -DCMAKE_LIBRARY_PATH=/path-to-Coin/lib ..."
		)
	ENDIF (COIN_LIBRARY)
ENDIF (NOT COIN_LIBRARY_FOUND)

MARK_AS_ADVANCED(
	COIN_FOUND
	COIN_INCLUDE_DIR
	COIN_LIBRARY
	COIN_LIBRARY_RELEASE
	COIN_LIBRARY_DEBUG
	COIN_LIBRARY_STATIC
	COIN_LIBRARY_STATIC_RELEASE
	COIN_LIBRARY_STATIC_DEBUG
) 
